### ISSUE TITLE
Missing MusicBeatDetector 

### ISSUE THREAD

**Issue by annesteenbeek** [introlab/odas_ros#22]
I'm trying to install this package on ros_noetic using catkin build, and am unable to compile it following the instructions.
I've also tried older checkouts but am unable to fix the issue. 
I'm not sure if it's because of odas_ros or audio_utils.

Any help would be appreciated.

```
Project 'odas_ros' tried to find library 'MusicBeatDetector'.  The library
  is neither a target nor built/installed properly.  Did you compile project
  'audio_utils'? Did you find_package() it before the subdirectory containing
  its code is included?
```

**Comment by mamaheux** [comment]
Can you fetch the submodules of audio_utils by running the following command in the audio_utils directory? This should fix your issue.
```bash
git submodule update --init --recursive
```

**Comment by roboav8r** [comment]
@annesteenbeek @mamaheux I had the same issue when trying to build the package using `catkin build odas_ros`. It still persisted even after doing a `git submodule update --init --recursive` in `audio_utils`.

It worked just fine when using `catkin_build` though.

**Comment by philippewarren** [comment]
Closing this as I believe that this was fixed in https://github.com/introlab/audio_utils/pull/22
