### ISSUE TITLE
Why the ROS GUI is updating super slowly?

### ISSUE THREAD

**Issue by Femtofirst** [introlab/odas_ros#29]
When it is running properly, the ROS GUI is providing dots continously and there will always be dots visible on the screen. However, when I start ROS, the display has a big delay in providing information - It repeats the loop of showing dots for 0.3 seconds and not showing anything for 0.3 seconds.

I have tried to restart the computer and replug the microphone, does not work.
Can anyone help pls?

**Comment by philippewarren** [comment]
Duplicate
