### ISSUE TITLE
Sink tracks: Cannot connect to server

### ISSUE THREAD

**Issue by mamadouDembele** [introlab/odas_ros#4]
Hi I am currently working with the respeaker 4 mic array voice interface. I'm trying to find the location of the sound source thanks to the odas_ros packages. After compiling this package, when I run the launch, I first get this error '' Sink tracks: Cannot connect to server''.
![Screenshot from 2021-04-29 11-01-13](https://user-images.githubusercontent.com/57793779/116528780-81ddcb80-a8dc-11eb-8f34-b719cdf73c4b.png)

I said to myself as I had not launched odas studio, the error is surely due to that. So I first launched odas studio (npm start) then the launch file (roslaunch odas_ros odas.launch) I get a new error "error: [Errno 98] Address already in use"
![Screenshot from 2021-04-29 11-02-24](https://user-images.githubusercontent.com/57793779/116528861-94f09b80-a8dc-11eb-8151-5c47d03ae896.png)

Could someone help me

**Comment by dieserOnan** [comment]
Same Problem here. I also get the "odas_core_node-1 process has died" error. The Log only states 
`[0m[ INFO] [1621508840.451637201]: Using configuration file = /home/onan/catkin_ws/src/odas_ros/config/configuration.cfg[0m
[0m[ INFO] [1621508840.452201830]: | + Initializing configurations...... [0m
[0m[ INFO] [1621508840.517233145]: | + Initializing objects............. [0m
[0m[ INFO] [1621508840.740398386]: | + Launch threads................... [0m
Sink pots: Cannot connect to server
Sink tracks: Cannot connect to server`

Do I need to configure something different to the pure Odas standalone?

Any help is appreciated :)
