### ISSUE TITLE
odas_ros config problem for ReSpeaker USB mic array

### ISSUE THREAD

**Issue by adsasdasdfdfsd** [introlab/odas_ros#9]
I got some errors when configure for ReSpeaker USB mic array. This device has 4 mics. 

If I set the nBits = 32, I got the error: "Source hops: Cannot set sample format: Invalid argument".  
If I set the nChannels = 4, I got the error: "Source hops: Cannot set channel count: Invalid argument".

It's still working with this default config anyway:
raw: 
{
    fS = 16000;
    hopSize = 128;
    nBits = 16;
    nChannels = 6; 
...

Is there a ref configuration for the ReSpeaker USB mic array?
Quan

**Comment by ibov** [comment]
PS. the odas_ros node runs for 72s then all topics stop publishing.

**Comment by ELELUABDULSALAM** [comment]
check your soundcard

**Comment by ibov** [comment]
thanks
